services:
  db:
    image: postgres:17
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    # for Swarm 
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "8081:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - backend_net
    environment:
      - prometheus_multiproc_dir=/tmp/metrics
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - metrics_data:/tmp/metrics
    security_opt:
      - no-new-privileges:true
    # for Swarm 
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
  
  prometheus:
    image: prom/prometheus:v3.5.0
    restart: always
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      app:
        condition: service_healthy
        restart: true
      node-exporter:
        condition: service_started
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
    # for Swarm 
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  grafana:
    image: grafana/grafana:12.1
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    tmpfs:
      - /var/log/grafana
      - /tmp
    read_only: true
    ports:
      - "3000:3000"
    depends_on:
      prometheus:
        condition: service_healthy
        restart: true
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    # for Swarm 
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "512M"

  node-exporter:
    image: prom/node-exporter:v1.9.1
    restart: always
    ports:
      - "9100:9100"
    read_only: true
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9100/"]
      interval: 30s
      timeout: 5s
      retries: 3
    # for Swarm 
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "128M"


volumes:
  db_data:
  grafana_data:
  prometheus_data:
  metrics_data:

networks:
  backend_net:

