x-healthcheck-default: &default-healthcheck
  interval: 10s
  timeout: 5s
  retries: 3


services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "testdb"]
      <<: *default-healthcheck
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8081:8000"
    depends_on:
      - db
    networks:
      - backend_net
    environment:
      - prometheus_multiproc_dir=/tmp/metrics
    volumes:
      - metrics_data:/tmp/metrics
  
  prometheus:
    image: prom/prometheus:v3.5.0
    restart: always
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - app
      - node-exporter
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      <<: *default-healthcheck

  grafana:
    image: grafana/grafana:12.1
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      <<: *default-healthcheck

  node-exporter:
    image: prom/node-exporter:v1.9.1
    restart: always
    ports:
      - "9100:9100"
    networks:
      - backend_net


volumes:
  db_data:
  grafana_data:
  prometheus_data:
  metrics_data:

networks:
  backend_net:

