services:

  db:
    image: postgres:17
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "1024M"
  
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on: 
      - db
    env_file: .env
    environment:
      - prometheus_multiproc_dir=/tmp/metrics
    volumes:
      - metrics_data:/tmp/metrics
    tmpfs:
      - /tmp
    read_only: true
    security_opt:
      - no-new-privileges:true
    ports:
      - "8081:8000"
    networks:
      - backend_net
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "256M"
  
  prometheus:
    image: prom/prometheus:v3.5.0
    depends_on:
      - app
      - node-exporter
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/:ro
      - prometheus_data:/prometheus
    networks:
      - backend_net
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"

  grafana:
    image: grafana/grafana:12.1.1
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    tmpfs:
      - /var/log/grafana
      - /tmp
    read_only: true
    ports:
      - "3000:3000"
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "512M"

  node-exporter:
    image: prom/node-exporter:v1.9.1
    read_only: true
    ports:
      - "9100:9100"
    networks:
      - backend_net
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9100/"]
      interval: 30s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "128M"

volumes:
  db_data:
  grafana_data:
  prometheus_data:
  metrics_data:

networks:
  backend_net:

