name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install -r app/requirements-dev.txt
      - name: Run tests
        run: |
          pytest -q
      - name: Lint (ruff)
        run: |
          ruff check app
      - name: Format (black)
        run: |
          black --check app
          
  integration-test:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and start services with docker-compose
        run: |
          docker compose up --build -d
      - name: Wait for app to be healthy
        run: |
          for i in {1..10}; do
          	STATUS=$(docker inspect --format='{{.State.Health.Status}}' docker_lab-app-1 2>/dev/null || echo "no-health")
                  if [ "$STATUS" = "healthy" ]; then
                  	echo "Container is healthy"
                  	exit 0
          fi
          	echo "No healthcheck configured"
          	exit 1
          done
      - name: Tear down compose stack
        if: always()
        run: |
          docker compose down

  build-and-scan:
    needs: test-and-lint
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.IMAGE }}
    steps:
      - id: set-image
        run: |
          IMAGE="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t ${{ steps.set-image.outputs.IMAGE }}:latest -t ${{ steps.set-image.outputs.image }}:${{ github.sha }} app
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ steps.set-image.outputs.IMAGE }}:latest
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push Docker image
        run: |
          docker push ${{ steps.set-image.outputs.IMAGE }}:latest
          docker push ${{ steps.set-image.outputs.IMAGE }}:${{ github.sha }}

  deploy:
    needs: 
      - build-and-scan 
      - integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Deploy with Docker Compose
        run: |
          echo "Deploying ${{ needs.build-and-scan.outputs.IMAGE }}:latest"
          docker pull ${{ needs.build-and-scan.outputs.IMAGE }}:latest
          docker compose -f docker-compose.yml up -d
