name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt \
            app/requirements-dev.txt

      - name: Run tests
        run: |
          pytest -q

      - name: Lint (ruff)
        run: |
          ruff check .

      - name: Format (black)
        run: |
          black --check .
          
  integration-test:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and start services with docker-compose
        run: |
          docker compose up --build -d
      - name: Wait for services to be healthy
        run: |
          wait_for_healthy() {
            local name=$1
            for i in {1..10}; do
              STATUS=$(docker inspect --format='{{.State.Health.Status}}' "$name" 2>/dev/null || echo "no-health")
              echo "Attempt $i: $STATUS"
              if [ "$STATUS" = "healthy" ]; then
                echo "$name is healthy"
                return 0
              fi
              sleep 3
            done
            echo "$name did not become healthy after 10 attempts"
            return 1
          }
          wait_for_healthy docker_lab-db-1
          wait_for_healthy docker_lab-app-1
          wait_for_healthy docker_lab-prometheus-1
          wait_for_healthy docker_lab-grafana-1

      - name: Database backup script test
        run: |
          ./backup.sh
          test -n "$(find backups -type f -name 'backup_*' -mmin -1)"

      - name: Tear down compose stack
        if: always()
        run: |
          docker compose down

  build-and-scan:
    needs: test-and-lint
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.set-image.outputs.IMAGE }}
    steps:
      - id: set-image
        run: |
          IMAGE="ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE=$IMAGE" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.set-image.outputs.IMAGE }}:latest -t ${{ steps.set-image.outputs.image }}:${{ github.sha }} app

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ steps.set-image.outputs.IMAGE }}:latest
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
          output: trivy-report.sarif
          format: sarif

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-report.sarif 

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ steps.set-image.outputs.IMAGE }}:latest
          docker push ${{ steps.set-image.outputs.IMAGE }}:${{ github.sha }}

  deploy:
    needs: 
      - build-and-scan 
      - integration-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Deploy with Docker Compose
        run: |
          echo "Deploying ${{ needs.build-and-scan.outputs.IMAGE }}:latest"
          docker pull ${{ needs.build-and-scan.outputs.IMAGE }}:latest
          docker compose -f docker-compose.yml up -d
