name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install -r app/requirements-dev.txt
      - name: Run tests
        run: |
          pytest -q
      - name: Lint (ruff)
        run: |
          ruff check app
          
  integration-test:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and start services with docker-compose
        run: |
          docker compose up --build -d
      - name: Wait for app to be healthy
        run: |
          for i in {1..10}; do
            docker inspect --format='{{json .State.Health.Status}}' app | grep -q healthy && break
            sleep 3
          done
      - name: Run integration tests
        run: |
          pytest -q
      - name: Tear down compose stack
        if: always()
        run: |
          docker compose down

  build-and-scan:
    needs: test-and-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t docker_lab:ci app
      - name: Install trivy
        run: |
          sudo apt-get update && sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.65.0/trivy_0.65.0_Linux-64bit.deb -O /tmp/trivy.deb
          sudo dpkg -i /tmp/trivy.deb
      - name: Scan image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 docker_lab:ci || true
